---
platform: linux

inputs:
- name: stemcell
- name: os-conf-release

params:
  BOSH_CLIENT: ~
  BOSH_CLIENT_SECRET: ~
  BOSH_CA_CERT: ~
  BOSH_DEPLOYMENT: ~
  BOSH_ENVIRONMENT: ~
  BOSH_JUMPBOX_IP: ~
  BOSH_JUMPBOX_PRIVATE_KEY: ~
  BOSH_JUMPBOX_USER: ~
  BOSH_STEMCELL_OS: ~
  BOSH_STEMCELL_NAME: ~

run:
  path: os-conf-release/ci/tasks/run-acceptance-tests.sh
