#!/bin/bash

echo "`date`: Queued disable agent"

(
  echo "`date`: In 60 secs..."
  sleep 60
  echo "`date`: Killing bosh-agent"
  killall bosh-agent
  echo "`date`: Stopping bosh-agent permanently"
  sv stop agent
) &

disown

exit 0
