#!/bin/bash

echo "`date`: Queued disable agent"

(
  echo "`date`: In 60 secs..."
  sleep <%= p("wait_before_killing") %>

  echo "`date`: Stopping bosh-agent permanently"
  sv stop agent

  echo "`date`: Killing bosh-agent just in case"
  sv kill agent

  mv /var/vcap/bosh/bin/bosh-agent{,-os-conf-disabled}
) &

disown

exit 0
